language: node_js
sudo: false

node_js:
  - "5"
  - "4"
addons:
  postgresql: "9.3"

services:
  - postgresql

cache:
  directories:
    node_modules

after_script:
  npm run coverage

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
